#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].system_twn > "/dev/null"; then
	uci -q batch <<-EOF
		set system.@system[0].timezone="CST-8"
		set system.@system[0].zonename="Asia/Taipei"

		delete system.ntp.server
		add_list system.ntp.server="time.google.com"
		add_list system.ntp.server="time.cloudflare.com"

		set system.@imm_init[0].system_twn="1"
		commit system
	EOF
fi

opkg_mirror="$(uci -q get system.@imm_init[0].opkg_mirror)"
if [ -z "$opkg_mirror" ]; then
	opkg_mirror="https://mirrors.vsean.net/openwrt"
	uci -q batch <<-EOF
		set system.@imm_init[0].opkg_mirror="$opkg_mirror"
		commit system
	EOF
fi

sed -i.bak "s,https://downloads.immortalwrt.org,$opkg_mirror,g" "/etc/opkg/distfeeds.conf"

exit 0
